### ISSUE TITLE
TBI - Set up SonarQube

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#108]
### Description (include screenshots)

For continuous inspection of code quality 
To Detect bugs

### Value
Optional - details on how this technical backlog item provides value to end-users or dev team eg. Performance, Quality, Maintainability. This will help determine the ranking in relation to feature development

### Architecture Elaboration
None

### Tasks
- [x] Add SonarQube scan to pipeline

**Comment by carwelsh** [comment]
@Klaus-Keller FYI

**Comment by Klaus-Keller** [comment]
@kranthie-sap opened a ticket to [Add SonarCloud GitHub App for guided-answers-extension Repository #803](https://github.wdf.sap.corp/OSPO/OSPO-request/issues/803)
