### ISSUE TITLE
FEATURE - EXT - Minimum Contrast 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#135]
**As a user, I want to set my preferences to high contrast so that I can view the GA according to my viewing preferences**

### Description
 The visual presentation of text and images has to have a minimum  contrast ratio of at least 4.5:1, 

The intent of this is to provide enough contrast between text and its background so that it can be read by people with moderately low vision (who do not use contrast-enhancing assistive technology).

### Acceptance Criteria

**Given** the user has opened GA 
**when** the user select high contrast as their colour preference
**then** the user will see that all elements of the GA screen will be outlined clearly 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by sanat-thukral** [comment]
FYI: this feature has gone through a design review by Colin, Aisling and Richard
