### ISSUE TITLE
BUG - Guided Answers shows a branch which does not exist

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#139]
### Related Feature
Feature request: Initial Release

### Description
Guided Answers shows a branch which does not exist 

### Steps to Reproduce
**Part 1**
1. Launch GA web application 
https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:45996:50742
// Here you will notice that only 1 branch is there: `Cloud Foundry`

**Part 2**
1. Now in VSCode, launch `Guided Answers extension by SAP`
2. Navigate to the same exact location where you are in `Part 1` above.
i.e. SAP Fiori tools->Deployment->SAP Business Appplication Studio
3. Click on `ABAP on premise`

### Expected results
`ABAP on premise` is not shown

### Actual results

`ABAP on premise` is shown (See screenshots below)

### Screenshots
View in Guided Answers web application:
![image](https://user-images.githubusercontent.com/59027566/176107336-02ae8d48-58d9-492c-b11c-1218ca3517b9.png)

View in VSCode extension:
![image](https://user-images.githubusercontent.com/59027566/176107260-d5621629-1394-440c-aae4-fe64f087b6f5.png)

#### Version/Components/Environment	
Guided Answers extension version: https://github.com/SAP/guided-answers-extension/releases/download/sap-guided-answers-extension%400.4.0/sap-guided-answers-extension-0.4.0.vsix
 
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by Klaus-Keller** [comment]
Hi @theStiggySpd,

Here is the API call response for the node 50742: https://ga.support.sap.com/dtp/api/nodes/50742

```
{
  NODE_ID: 50742,
  TITLE: "SAP Business Application Studio",
  BODY: "<p>In SAP Business Application Studio, what is the target environment you are deploying to?</p>",
  QUESTION: "I'm deloying to...",
  EDGES: [
    {
      LABEL: "Cloud Foundry",
      TARGET_NODE: 51205,
      ORD: 1
    },{
      LABEL: "ABAP On Premise",
      TARGET_NODE: 51206,
      ORD: 2
    }
  ]
}
```

<img width="861" alt="2022-06-28_09-00-14" src="https://user-images.githubusercontent.com/66327622/176114496-76c3b87b-7c5f-48e3-bb6d-6716bf5c892a.png">


I clearly returns two `EDGES`.
Perhaps a server caching issue? Was there recently a change to the node?
@JonWiens, can you help here?

**Comment by theStiggySpd** [comment]
ok i found the reason. So, in editor, we had added the outcome as `ABAP on premise` but never filled in the details.
Guided Answers web application in that scenario does not shows the outcome, where extension via API which still shows valid outcome (even though content is empty).
I removed this empty outcome and issue went away. We should still handle this gracefully. Lets see what @JonWiens suggests?

**Comment by carwelsh** [comment]
@theStiggySpd - When you preview a Guided Answer with an outcome that has no details it is simply just not shown. Should we not follow this approach in the extension? If there is no content to show why show the option?

**Comment by Klaus-Keller** [comment]
@carwelsh: while I believe we could address this issue on extension side, I strongly recommend that the API should return only valid `EDGES`. @JonWiens what do you think?

**Reason**
If we as consumer would address this, we need to load all `EDGES` (nodes behind buttons) and validate them, which might have a negative impact on performance. Just think of a scenario where we have many options, like this one:
https://ga.support.sap.com/dtp/viewer/index.html#/tree/1910/actions/24709:34441

![2022-08-01_11-23-32](https://user-images.githubusercontent.com/66327622/182218269-3d016a1c-cc28-47b1-b73c-382696393f4c.png)


In this case, we would need to perform 13 (!) additional requests just to check if all of the options (`EDGES`) are valid nodes.

**Comment by carwelsh** [comment]
@Klaus-Keller @JonWiens - Yes I agree this would be a better approach.

**Comment by Klaus-Keller** [comment]
@carwelsh and @ritarora, do you know if this is still an issue or has this been fixed on API side? Could you please retest?

**Comment by Klaus-Keller** [comment]
@carwelsh, I think we've tried to reproduce this in a meeting but have not been able to, so I guess this is solved on API side.
