### ISSUE TITLE
TBI - EXT - Add unit test to ide-extension

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#172]
### Description (include screenshots)
Increase unit test coverage for module [`sap-guided-answers-extension`](https://github.com/SAP/guided-answers-extension/tree/main/packages/ide-extension).

### Value
Code quality 

### Tasks
- [ ] Add unit tests to increase test coverage

**Comment by Klaus-Keller** [comment]
> @Klaus-Keller FYI - Do you want to fill out the details?

Done

**Comment by Klaus-Keller** [comment]
Has been fixed a while ago:
![image](https://user-images.githubusercontent.com/66327622/197010425-adfdcc73-8d9a-4b94-9db4-a6a4b2148c07.png)
https://sonarcloud.io/component_measures?metric=coverage&selected=SAP_guided-answers-extension%3Apackages&id=SAP_guided-answers-extension
