### ISSUE TITLE
BUG - UX - Incorrect padding in search result tile with no description

### ISSUE THREAD

**Issue by ritarora** [SAP/guided-answers-extension#234]
### Related Feature
Feature request: Home page - https://github.com/SAP/guided-answers-extension/issues/89 

### Description
When there is no description for a Guided Answer in search results tile, the padding of the title is incorrect 

### Steps to Reproduce
1. Go to home page
2. Add the Search term 'AD SSO'
3. Search results are loaded
4. Scroll to the tile with title' AD SSO is failing....' 
5. Padding of the Tile (H3 )is incorrect

### Expected results
Search result tile is rendered with correct padding and spacing

### Actual results
There is space around H3

### Screenshots
<img width="776" alt="Screenshot 2022-09-09 at 09 08 21" src="https://user-images.githubusercontent.com/43745372/189322558-7a4e6195-a261-4d3d-b20c-6315472e644d.png">

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by ritarora** [comment]
FYI @gpeuc, can you please add the design for the correct padding in such a case

**Comment by gpeuc** [comment]
<img width="757" alt="Screenshot 2022-09-09 at 15 09 36" src="https://user-images.githubusercontent.com/44162846/189369603-6d5e1186-c3cf-43a2-ac89-7bc2988639db.png">

It's in Figma!

**Comment by ritarora** [comment]
@gpeuc this is now fixed, can you please validate if this is ok

**Comment by gpeuc** [comment]
Ha! All good 👍
