### ISSUE TITLE
BUG - UX - Hover on the last node is wonked

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#239]
There's something wonky happening with hover on last node.

Expected result is that literally nothing happens. No hover effects, no mouse effects, nothing. It's just a plain old boring node. But what happens is that border changes, and there's a brief 1-frame, blitz of mouse cursor going to `pointer`. Can we please fix this?

![last node](https://user-images.githubusercontent.com/44162846/189856192-7b4d659e-a0f7-48ee-9bd5-f76e59948e92.gif)

@ritarora

**Comment by unseen1980** [comment]
@gpeuc I tried both in vscode and in sbas and various themes, but I can't reproduce it. I tried moving the cursor as slowly as possible 😅! Please check again. Several styling fixes went in since September, so maybe is not an issue anymore. Thanks

**Comment by gpeuc** [comment]
@unseen1980 Hey, yes this seems to have been fixed in the meantime! Yay!
