### ISSUE TITLE
FEATURE - Introduce opening Guided Answer open to side when called via other extensions

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#263]
_As a developer using other tools like SAP Fiori tools which open Guided Answers extension for troubleshooting,
I want to see Guided Answers `open to the side` when being called by other extensions,
so that I have both Guided Answers and other extensions opened side-by-side for more better UX and troubleshooting

### Description

- This feature will open Guided Answers `to the side` only when called from other extensions.
- The main command `SAP: Open Guided Answers` should always open in Full SCreen mode (as it was before)
- E.g. SAP Fiori generator and Guided ANswers side by side
 
![image](https://user-images.githubusercontent.com/59027566/194468160-a480c0b1-b0b1-4f43-b096-0dbf1991e6a0.png)

### Technical Design

@Klaus-Keller to add

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have experienced an issue in SAP Fiori tools Fiori Generator (Or any other product) 
**when** I am shown to troubleshoot this issue via Guided Answers
**then** Guided Answers should open to the side

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by sanat-thukral** [comment]
The first PR for this story(#350)  that has been merged didn't follow the exact requirements of the story. As it opened GA to the side when any other window was opened in the editor, not when GA was called from another extension. A new PR (#353) has been created to override the first PR with the correct functionality.

**Comment by Klaus-Keller** [comment]
PR is merged, closing this ticket.
