### ISSUE TITLE
FEATURE - EXT - Add Pagination to returned search list

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#270]
_As a user, I want to be able to page through the returned search results or default list so that I am not shown a big list right away which might impact the performance_

### Description

Pagination delivers structure to the returned Guided Answers list 
Pagination supports navigation (and in particular back and forward).
Pagination typically means smaller, shorter pages and as a result reduced load times.
Pagination, and shorter pages in general, can help in terms of overall navigation.

### Technical Design
- 2 new parameters that will allow paging. Eg.
https://ga.support.sap.com/dtp/api/v2/trees/*?responseSize=2&offset=1
Here:
**responseSize** influences the maximum number of trees returned in the “trees” array.  20 is a default value.
**offset** sets the number of rows that should be skipped before the beginning of the result set.
Using these two values will allow for paging through the results.

- **resultSize** property which indicates the total result set size so we know how many matches there are to the search query despite the responseSize limit.
https://ga.support.sap.com/dtp/api/v2/trees/hana%20upgrade?responseSize=2&offset=1
(ordered by score desc and alphabetically in the case of ties).

### Acceptance Criteria
- Given I am searching in Guided Answers extension,
- when I am shown the results which matches search criteria
- then result view should paginate the list

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment]
@theStiggySpd - Please add further details if need.  We will need some designs from Goran.

**Comment by theStiggySpd** [comment]
hi @carwelsh @unseen1980 i have added some more relevant info here. Please have alook and we can discuss details in our next meeting
