### ISSUE TITLE
BUG -  Not Solved options missing opening the community link

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#272]
### Related Feature
Feature request: https://github.com/SAP/guided-answers-extension/issues/96

### Description
As per https://github.com/SAP/guided-answers-extension/issues/96 user is presented various options if issue is not resolved. 
It should also include `Ask the community`

### Steps to Reproduce
1. Open GA 
2. Navigate to end of any guide
3. Click on `This did not solve my issue`

### Expected results
There should be an option `Ask the SAP Community` above `Search for another Guided Answer` which should point to `https://answers.sap.com/index.html`

### Actual results
no `Ask the SAP Community`
![image](https://user-images.githubusercontent.com/59027566/196824482-872150d5-5249-4307-bbd2-345b1eb6f279.png)

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by unseen1980** [comment]
@carwelsh, we can close this. @sanat-thukral merged a fix a few weeks ago, and I just verified that the missing option is there.

<img width="1136" alt="Screenshot 2022-11-14 at 10 43 39" src="https://user-images.githubusercontent.com/2386570/201640628-7d944d37-d478-46f6-93db-9b47f750a74f.png">
