### ISSUE TITLE
BUG - Search page bugs (November)

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#299]
Hey all,

Following the demo, I saw some bugs, so I'll just report them:

- Active icon should change SVG colour to `var(--vscode-button-foreground)`, for example, like GD does it already
<img width="145" alt="Screenshot 2022-11-03 at 16 07 34" src="https://user-images.githubusercontent.com/44162846/199773164-21b54b79-701c-4601-bf49-41941d491176.png">

<img width="79" alt="Screenshot 2022-11-03 at 16 08 07" src="https://user-images.githubusercontent.com/44162846/199773295-2e8e40f5-a19b-45ae-b9e1-e0c80bae5311.png">

- Clear filters button is wonky, rather imprecise. It also touches the text on the left when hover effect is turned on.

<img width="172" alt="Screenshot 2022-11-03 at 16 09 21" src="https://user-images.githubusercontent.com/44162846/199773542-05f35eef-4ffa-4502-adb3-2e675daee062.png">

Please properly align icon with the text, and tighten up the whole thing.

<img width="213" alt="Screenshot 2022-11-03 at 16 13 13" src="https://user-images.githubusercontent.com/44162846/199774470-a6c860b4-c67c-40dc-a913-dfc956d81366.png">

- On scroll we lose the header with search bar. Let's not do that. Let's keep the search and header locked at the top, otherwise users have to scroll back to get to the search.

- Blue focus border is clipped. On the first element top/left/right is clipped, and on other ones left/right is clipped.

<img width="933" alt="Screenshot 2022-11-03 at 16 15 11" src="https://user-images.githubusercontent.com/44162846/199774953-7fc8981f-d62e-401e-9e62-5bd1110df6e8.png">

<img width="939" alt="Screenshot 2022-11-03 at 16 15 46" src="https://user-images.githubusercontent.com/44162846/199775090-2559a2c7-a263-4f03-b1a0-8222de330cd6.png">

Use negative outline offset to push it inside, so it doesn't get clipped on the outside

<img width="224" alt="Screenshot 2022-11-03 at 16 17 04" src="https://user-images.githubusercontent.com/44162846/199775402-fc85fd41-bc92-4e1b-84fd-9370ad6ce2a5.png">

- We are using wrong loader. We should also give it some bottom margin so it's not touching the end of the screen.

<img width="227" alt="Screenshot 2022-11-03 at 16 17 53" src="https://user-images.githubusercontent.com/44162846/199775594-9787f59b-4f11-46eb-ad1f-53351c020ac2.png">

We have it already built in UI Components.

<img width="349" alt="Screenshot 2022-11-03 at 16 19 18" src="https://user-images.githubusercontent.com/44162846/199775929-6da0eb64-68c7-49ee-be54-e3b53d3978b3.png">

- - - - 

@ckoutsiaris  @carwelsh

**Comment by theStiggySpd** [comment]
@gpeuc Can you please confirm from your side? 
Get the latest version here: https://github.com/SAP/guided-answers-extension/releases/tag/sap-guided-answers-extension%401.4.0

I did see some improvements but please confirm from your point of view:
- [ ] Active icon should change SVG colour
- [ ] Clear filters button is wonky, rather imprecise. It also touches the text on the left when hover effect is turned on.
- [ ] Please properly align icon with the text, and tighten up the whole thing.
- [ ] Blue focus border is clipped. On the first element top/left/right is clipped, and on other ones left/right is clipped.

**Comment by theStiggySpd** [comment]
>On scroll we lose the header with search bar. Let's not do that. Let's keep the search and header locked at the top, otherwise users have to scroll back to get to the search.

I see that now with the above mentioned version, search bar and header remains locked up BUT only for little bit. If i scroll down further, it disappears.
@gpeuc I think thats not what you want right?

**Comment by gpeuc** [comment]
@theStiggySpd yes, it should just remain there all the time. There is no benefit in hiding it, and it's just annoying if you have to modify the search. So there are zero wins, and some annoyances.

**Comment by sanat-thukral** [comment]
Sorry missed this comment. I can create a new PR to address this issue @theStiggySpd @gpeuc

**Comment by sanat-thukral** [comment]
Update: All bugs mentioned above have been fixed in #335 except for the sticky header. It will be addressed in another PR.
