### ISSUE TITLE
BUG -  General Feedback Message sent pop up still remains when you re visit the tree 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#306]
### Related Feature
Feature request: _issue number_

### Description
Message sent pop up still displays when you re visit the tree 

### Steps to Reproduce
1. Open GA 
2. Select Fiori tools tree 
3. Select out come
4. Submit General Feedback  - Message sent appears and then fades away 
5. Navigate back to the home screen
6. Select any tree 

### Expected results

Guide appears 

### Actual results

Guide appears with the 'Message Sent' pop up displaying which fades away.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by carwelsh** [comment]
FYI

**Comment by carwelsh** [comment]
@theStiggySpd FYI

**Comment by theStiggySpd** [comment]
this is fixed. Tested on both BAS and VSCode with version https://github.com/SAP/guided-answers-extension/releases/tag/sap-guided-answers-extension%401.4.0

**Comment by theStiggySpd** [comment]
@unseen1980 @Klaus-Keller Thanks for your help.
