### ISSUE TITLE
BUG - Home icon is squished

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#328]
I've just noticed that the Home button icon is squished. 

<img width="195" alt="Screenshot 2022-12-09 at 10 11 11" src="https://user-images.githubusercontent.com/44162846/206678342-3bbdc12f-a28c-47c8-a151-294495728b4e.png">

It renders as 13px wide.

<img width="351" alt="Screenshot 2022-12-09 at 10 11 50" src="https://user-images.githubusercontent.com/44162846/206678443-662a641a-6ed6-48b6-870c-f09e224dd951.png">

And the reason for that it would seem is that the button has artificial size put on it (instead of letting it just be as wide as it needs to be)

<img width="199" alt="Screenshot 2022-12-09 at 10 12 16" src="https://user-images.githubusercontent.com/44162846/206678517-cf5c6977-e3da-4b64-aacb-436d068f1740.png">

If I remove this `width`

Then the icon jumps to the natural size of 16x16

<img width="351" alt="Screenshot 2022-12-09 at 10 13 17" src="https://user-images.githubusercontent.com/44162846/206678681-fc6fc793-0ceb-4520-9728-d29f5ca376e4.png">

**Comment by Klaus-Keller** [comment]
This has been fixed, closing this issue.
