### ISSUE TITLE
BUG - Feedback icon is most likely hard-coded

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#331]
This chat icon is most likely hard-coded. I cannot catch it because it disappears too quickly, but just by looking at this, it seems like it uses hex.

Of course, it should not use hex, it should be a variable. 

`--vscode-icon-foreground`

<img width="457" alt="Screenshot 2022-12-09 at 10 35 53" src="https://user-images.githubusercontent.com/44162846/206683100-c7c3dfb0-86db-48b4-bd41-bbf9fc763ea4.png">

**Comment by gpeuc** [comment]
Oh, also, it's wrong icon.

This is how it should be:

[Message sent.svg.zip](https://github.com/SAP/guided-answers-extension/files/10194243/Message.sent.svg.zip)

Bubble: `--vscode-icon-foreground`
Blue check is: `--vscode-focusBorder`

<img width="552" alt="Screenshot 2022-12-09 at 11 23 52" src="https://user-images.githubusercontent.com/44162846/206691911-8edcf1b6-31cc-49bd-b913-79168a1c50b5.png">

**Comment by Klaus-Keller** [comment]
This issue has been fixed, closing this ticket.
