### ISSUE TITLE
TBI - EXT - Consume HTML enhancement API

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#408]
### Description (include screenshots)
Consume HTML enhancements from GA API
 
We will no longer require enhancement.json , all enhancements will be stored and managed in the GA Editor

### Value

All Guided Answer content is now managed in the editor. 

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by theStiggySpd** [comment]
This works perfectly now. 
Thanks for working on this @Klaus-Keller
