### ISSUE TITLE
BUG - link in light theme getting invisible

### ISSUE THREAD

**Issue by Klaus-Keller** [SAP/guided-answers-extension#423]
### Related Feature
Feature request: Link in Guided Answer content

### Description
On hover over a link in Guided Answers extension, the link gets invisible.

### Steps to Reproduce
1. To navigate to a Guided Answer node that contains a link, e.g. by copy & paste this in your browser 
   ```
   vscode://saposs.sap-guided-answers-extension#/tree/3046/actions/45995:48363
   ```
3. Make sure you have light theme in Visual Studio Code
4. Hover over a link

### Expected results
Link is still visible

### Actual results
Link is hidden

### Screenshots
![2023-03-09_08-52-16 (1)](https://user-images.githubusercontent.com/66327622/224097634-190bb786-a534-48e6-b0ef-5144a035ecee.gif)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by gpeuc** [comment]
We have this in the Storybook. 

This thing is wrong for text links. Should just remove text decoration, that's it.

<img width="410" alt="Screenshot 2023-03-13 at 11 12 18" src="https://user-images.githubusercontent.com/44162846/224685640-94e787a4-f650-4562-8884-48a9f941b8f0.png">

![2023-03-13 11 10 25](https://user-images.githubusercontent.com/44162846/224685357-04a06d2d-82e3-403c-a858-f5d2af94afe1.gif)

**Comment by Klaus-Keller** [comment]
Fixed with https://github.com/SAP/guided-answers-extension/pull/427
