### ISSUE TITLE
BUG - EXT - Keyboard navigation through GA returned list when filter is applied

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#434]
### Related Feature
Feature request: _issue number_

### Description

Users are unable able to navigate through the returned GA list when a filter has been applied to the list. 

It is possible when no filter is applied

When the clear filter link is selected /highlighted  the tab control doesn't give focus to the returned list it tabs out of the application. 

### Steps to Reproduce
Steps to reproduce the behaviour:
1. Open GA extension
2. Enter search criteria and apply a filter 
3. Using the keyboard tab from search input field to the returned GA list

### Expected results

User can tab to the returned list 
### Actual results
User cannot tab to the returned list when a filter has been applied.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by oliversberzs** [comment]
@carwelsh fixed & merged
