### ISSUE TITLE
BUG - EXT - Applied Filters appear in the Guided Answers content screens

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#442]
### Related Feature
Feature request: _issue number_

### Description
Applied Filters appear in the Guided Answers content screens

When a user applies a filter on the Guided Answers list that filter still appears to the user after the user selects a Guided Answer. The filter is no longer relevant at this point. 

This is regression

It happens in both VSCode and SBAS

### Steps to Reproduce
1. Open GA 
2. Apply a filter - Filter is applied and shown on the home screen 
3. Select a Guided Answer

### Expected results

The guided answer is shown with no filter information being displayed

### Actual results

The guided answer is shown with filter information being displayed. 
### Screenshots
![Screenshot 2023-03-29 at 11 41 27](https://user-images.githubusercontent.com/9609226/228510148-ed41e53f-cde2-4d30-aeec-1e26ad5786d8.png)
![Screenshot 2023-03-29 at 11 42 16](https://user-images.githubusercontent.com/9609226/228510152-cae25741-3426-4aa8-a73d-8a73fc8791f0.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by oliversberzs** [comment]
@carwelsh @ritarora fixed & merged
