### ISSUE TITLE
BUG - EXT - Button/ Icon selection is not polished when using keyboard

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#444]
### Related Feature
Feature request: _issue number_

### Description
The following links/buttons are not polished when using keyboard selections

### Steps to Reproduce
1. Open GA 
2. Use Keyboard to navigate through the tool from start to finish

### Expected results
Button selection is concistent

Highlight in blue, double lined and centered.

### Actual results
Clear filters link is not fully highlighted in blue
General feedback button has one blue link but shareable link icon has two 
The copy to clipboard icon is not centered. 

### Screenshots

One or Two lines
![Screenshot 2023-03-29 at 12 18 15](https://user-images.githubusercontent.com/9609226/228521102-5efb5be1-f788-4fdb-bf29-54bbecb7f773.png)
![Screenshot 2023-03-29 at 12 18 23](https://user-images.githubusercontent.com/9609226/228521118-05d229fb-fddf-4fd7-988b-bac843527cd8.png)

Clear Filters not fully highlighted
![Screenshot 2023-03-29 at 12 19 21](https://user-images.githubusercontent.com/9609226/228521111-fc33bebe-9f28-4bb2-b743-a722e66301c5.png)

Copy to clipboard not centered
![Screenshot 2023-03-29 at 12 20 05](https://user-images.githubusercontent.com/9609226/228521107-6a4696eb-3b4c-497a-adf9-9e01ed31a451.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by unseen1980** [comment]
@carwelsh please check again, thanks

**Comment by carwelsh** [comment]
tested
