### ISSUE TITLE
BUG - Copied shareable ID does not work (tested on published v1.19.0 and main v1.20.3)

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#479]
### Related Feature
Feature request: https://github.com/SAP/guided-answers-extension/issues/311

### Description
Copied shareable ID does not work 

### Steps to Reproduce
1. Launch GA
2. Goto any node and click on `Share this guide` button
3. Copy the generated id
4. Goto Home page and paste the ID and hit enter

### Expected results
User is taken to the guided

### Actual results
No results found

### Screenshots
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/59027566/233490319-fa5f9998-6720-4c4f-b09f-5457435eaa0e.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by carwelsh** [comment]
@Klaus-Keller Could the fix this bug caused this bug? It is something similar to this bug

https://github.com/SAP/guided-answers-extension/issues/443

@theStiggySpd FYI

**Comment by Klaus-Keller** [comment]
Doesn't happen with https://ga.support.sap.com, seems to be an  internal issue.
