### ISSUE TITLE
BUG - EXT - VSCode link doesn't work on different API host 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#487]
### Related Feature
Feature request: _issue number_

### Description

VSCode link doesn't work on different API host 

https://gad5158842f.us2.hana.ondemand.com

### Steps to Reproduce
1. Change GA API host to https://gad5158842f.us2.hana.ondemand.com
2. Open GA 
3. Navigate through a Guide
4. Share guide
5. Copy to clipboard
6. Paste vscode link into search input - 

### Expected results

Guide opens

### Actual results
Nothing happens

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by Klaus-Keller** [comment]
Fixed in backend
