### ISSUE TITLE
FEATURE - Add ability to bookmark a guide for faster access

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#490]
_As a **developer or support colleague (in a particular area)**,
I want to **bookmark 1 or more guided answers node/branch in my list view**,
so that I **can have faster access to the most relevant guides needed during my development and also during support**_

### Description

- This feature will help end users who are supporting customers in a specific area. They will not have to search everytime. This will also enable FASTER acess to relevant guide encouraging sharing.
- This feature will enable a user to `BOOKMARK` a guided answer. This will help users faster access to guided answers of their relevant area.
  E.g. Bookmarks in Chrome Browser

- A user can remove this bookmarked guide at any time 

### UX Design
**Initial Proposals:**
- In guide detail view, Add a `star` icon next in the toolbar of each guide with tooltip `Bookmark this guide`
e.g. 
![image](https://user-images.githubusercontent.com/59027566/234468365-d0de5aed-4615-40e8-be64-41e09660e7e8.png)

- In List View, add a `star` icon on top right of each tile/list showing that the entry is bookmarked. User can click on start icon again to delete it as a bookmark

**Final Design**
 **In guide details page:**

- Toolbar will have a new star ⭐  icon in the toolbar. That icon, when clicked, saves the guide as a bookmark, and the star changes mode into full filled star  `--vscode-editorLightBulb-foreground`

- Clicking that yellow star will un-save the bookmark.

<img width="1000" alt="Deeper answers" src="https://user-images.githubusercontent.com/44162846/236175241-d5529620-c46b-433e-94ef-e486413ffa58.png">

**In Guide List Page/ Home page**

On the home page, when it's empty (so on first load, or when search input is zeroed out), we show the bookmarks.

Each bookmark block has a title that's comprised of 2 segments - the whole tree name + emdash separator + the actual node that was bookmarked. Special case here is if users bookmark the topmost node, then I suppose we only have one segment to show.

The list should be sorted by alphabet, and among other things, this will mean that nodes coming from the same parent tree will end up grouped together.

Once users start searching, bookmarks go away, and we just have search results.

<img width="1000" alt="List of answers with bookmarks" src="https://user-images.githubusercontent.com/44162846/236175846-52e4cc07-acea-4290-8d84-82c75255e6bc.png">

All of this actually also means that users could stumble upon the result which they've bookmarked in the search results. So we should add a star there to indicate this result has somewhere inside of it (since it could be a deep node).

<img width="1000" alt="List of answers" src="https://user-images.githubusercontent.com/44162846/236176591-01270b36-33fb-4abb-adcc-47c352df2347.png">

### Technical Design
TBA

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I launch Guided Answers extension
**when** I execute `SAP: Open Guided Answers`
**then** I should see my bookmarked guides (if any) by default

**Given** I am in the guide details view
**when** I click on the `star` icon
**then** this guide should be saved as bookmarked

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by gpeuc** [comment]
- All the bookmarked guides will appear first in the list view when GA is first launched
- The moment user searches, the list view will show results without any bookmarked guides

I've removed those, as those are solutions, not requirements. We can make better stuff.

**Comment by gpeuc** [comment]
## Bookmarks management

The nodes get a star ⭐  icon in the toolbar. That icon, when clicked, saves the guide as a bookmark, and the star changes mode into full filled star  `--vscode-editorLightBulb-foreground`

Clicking that yellow star will un-save the bookmark.

<img width="1920" alt="Deeper answers" src="https://user-images.githubusercontent.com/44162846/236175241-d5529620-c46b-433e-94ef-e486413ffa58.png">

**Comment by gpeuc** [comment]
## List of bookmarks

On the home page, when it's empty (so on first load, or when search input is zeroed out), we show the bookmarks.

Each bookmark block has a title that's comprised of 2 segments - the whole tree name + emdash separator + the actual node that was bookmarked.

The list should be sorted by alphabet, and among other things, this will mean that nodes coming from the same parent tree will end up grouped together.

<img width="1920" alt="List of answers with bookmarks" src="https://user-images.githubusercontent.com/44162846/236175846-52e4cc07-acea-4290-8d84-82c75255e6bc.png">

**Comment by gpeuc** [comment]
## Bookmarks in search

All of this actually also means that users could stumble upon the result which they've bookmarked in the search results. So we should add a star there to indicate this result has somewhere inside of it (since it could be a deep node).


<img width="1920" alt="List of answers" src="https://user-images.githubusercontent.com/44162846/236176591-01270b36-33fb-4abb-adcc-47c352df2347.png">

**Comment by theStiggySpd** [comment]
@gpeuc Great thanks much for the detailed updates.
