### ISSUE TITLE
FEATURE - Add ability to create shareable link with text instructions making it easier/standarized support communication

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#492]
_As a **support colleague responding to customer in a ticket or any form of communication**,
I want to **share a guide as a solution to their problem WITH BETTER instructions**,
so that they **ARE DISCOURAGED from going into web based GA, rather they stay within their IDE (SBAS/VSCODE) and open their guide**_

### Description

- This feature will ENHANCE and work in tandem with  the already existing `Share the Guide` option
- Currently, we are still noticing that web based URL are used. Which is not bad, but point of GA extension is to stay within the IDE
- This feature working with FEATURE - Add ability to bookmark a guide for faster access #490 will make it much faster and encourage users to use GA extension

### UX Design
**Initial Proposals**
- Add a new button next to already existing share link button (as shown below)
![image](https://user-images.githubusercontent.com/59027566/234952005-8ebc397a-4bb8-4d91-8c74-a012fb6ae03d.png)
- The tooltip of the button will be `Copy this link with instructions`
- When clicked, the following text will be copied
![image](https://user-images.githubusercontent.com/59027566/234954608-de67df5c-9f6d-49ad-8b76-faaa1fa71b27.png)

### FINAL VISUAL DESIGN 

https://www.figma.com/file/XSZw3w81MYY0QPe1BoUcBO/Guided-Answers?node-id=0-1&t=8baUYz9dCX2SCR3Q-0

### Technical Design
TBA

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a GA extension guide to share with customer
**when** I click on sharing the guide with complete instructions
**then** full steps text will be copied along with guide id, ready to share

1. On click of the share link the user will have the option to copy the link with instructions. 
2. On click of the 'Copy the link with instructions' the link is copied to the clipboard along with the out lined instructions. 
3. On paste of the link, the instructions appear with the link of the Guided Answer content embedded in the instructions. 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment]
@theStiggySpd - Which guide id do you want to be copied into the instructions? The VSCode link or just the Guide No# .

**Comment by gpeuc** [comment]
@carwelsh We are telling users in the instructions to open GA and then paste link into search, so I suspect it's whatever works for that scenario.

**Comment by carwelsh** [comment]
@gpeuc.  The instructions will work for both the VSCode and SBAS regardless if it is the VSCode direct link or just the Guided Answer number but I'm just thinking should we add some additional text such as , 'If you are using VSCode you can click directly on the link'  as this might save time for VSCode users as they will not have to follow the instructions step by step as the direct link will work for the.

**Comment by gpeuc** [comment]
@carwelsh Hey, any bit of help is good. Let's craft something that works and is helpful. Could you or @theStiggySpd paste here some working version of the text blurb, and we can then tinker around it to make it great.

**Comment by cjbernal** [comment]
@theStiggySpd I took a look as requested and had two thoughts: 
1. On the link to the node, I'm wondering if it might be more clear to users what we're linking to if you actually used the word `NodeCode` as it appears in the designs above. "Link" feels a bit ambiguous -- is it a link to the online version? A link to something else? What if the hyperlink text was something like: `Copy NodeCode [link] with instructions`? 

2. For the instruction text, I think subpoint B could be rearranged to focus on the action we want the users to take: `Paste the following link into the search input field and press Enter: <link>`

3. Also on the instruction text, I would start with a call to action (or at least the recommendation of an action) for your audience. Something like, `Learn more about the Guided Answers extension here: <link>`

**Comment by theStiggySpd** [comment]
> @theStiggySpd I took a look as requested and had two thoughts:
> 
> 1. On the link to the node, I'm wondering if it might be more clear to users what we're linking to if you actually used the word `NodeCode` as it appears in the designs above. "Link" feels a bit ambiguous -- is it a link to the online version? A link to something else? What if the hyperlink text was something like: `Copy NodeCode [link] with instructions`?
> 2. For the instruction text, I think subpoint B could be rearranged to focus on the action we want the users to take: `Paste the following link into the search input field and press Enter: <link>`
> 3. Also on the instruction text, I would start with a call to action (or at least the recommendation of an action) for your audience. Something like, `Learn more about the Guided Answers extension here: <link>`

Great thanks @cjbernal for your review. Based on it, I am adjusting the text as below. Skipping using NodeCode as in reality we are not using it. I would prefer something like Guide ID, Guide shortlink, something like that, which will remove the confusion of when to use a tree, node, branch, etc..We do not have to decide now. I will discuss with @carwelsh and get it updated later.

Ok here goes the final text (for now):
```
Please follow the steps mentioned in Guided Answers extension by SAP to resolve your issue:
a. Launch Guided Answers via the command `SAP: Open Guided Answers`
b. Paste the following guide shortlink into the search input field and hit Enter: <PLACEHOLDER_FOR_GUIDE_LINK>
c. Perform the steps as mentioned in the guide
Learn more about the Guided Answers extension here: https://github.com/SAP/guided-answers-extension

```
@oliversberzs Can you please update this text in your pr?

**Comment by oliversberzs** [comment]
@carwelsh @ritarora done & merged
