### ISSUE TITLE
BUG - Wonky position and animation of the search icon

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#504]
The search icon is misplaced a bit in the implementation. It should be a bit lower, and a bit less padding left/right around it. If this can eb fixed on the `ui-components` level, that would be even better.

I am also not sure that the animations play out correctly. You can perhaps see in the slow motion capture that the zoom lens jumps to the left and then disappears. It should just simply disappear and reappear, without any jumping.

![2023-05-18 10 46 58](https://github.com/SAP/guided-answers-extension/assets/44162846/d70bcc04-ecfc-4682-88d6-f744ce187999)

@oliversberzs

**Comment by oliversberzs** [comment]
@gpeuc done & merged

**Comment by theStiggySpd** [comment]
Validated with https://github.com/SAP/guided-answers-extension/releases/tag/sap-guided-answers-extension%401.23.6

@gpeuc Please feel free to reopen this issue if it needs more work
@oliversberzs thanks for the fix
