### ISSUE TITLE
BUG - Copy to clipboard jumps the text blow it 

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#505]
There's probably something a bit wrong with the metrics when the green confirmation appears, as it causes the text below it to jump up one pixel and it causes the Copy icon to move right. It looks glitchy. _(ignore the blue border instead of green, it's a problem with recording software)_

You can see in the individual sizing there's differences, that's why the things move. The green confirmation overlay needs to be exactly the size of the input so that it does not push stuff around.

![2023-05-18 11 03 18](https://github.com/SAP/guided-answers-extension/assets/44162846/2449d4e9-5f90-4d40-bccf-27110507b48c)

<img width="341" alt="Screenshot 2023-05-18 at 11 06 11" src="https://github.com/SAP/guided-answers-extension/assets/44162846/63b3be72-d9e7-4745-bbbb-14d3349051ec">

<img width="371" alt="Screenshot 2023-05-18 at 11 06 26" src="https://github.com/SAP/guided-answers-extension/assets/44162846/bf5d01cf-f290-4682-b531-b7719806e95a">

**Comment by oliversberzs** [comment]
@carwelsh @ritarora fixed & merged

**Comment by theStiggySpd** [comment]
@gpeuc Please validate and close this issue

**Comment by gpeuc** [comment]
Yeah, checked it with what @oliversberzs sent me, it's good.
