### ISSUE TITLE
TBI - Configure Guided Answers to be shown in the menu item of SBAS Welcome Page

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#506]
### Description (include screenshots)
With this TBI, Guided Answers extension will be configured so that SBAS Welcome page will show an option to launch Guided Answers from the new Menu item.

Sample configuration:
![image](https://github.com/SAP/guided-answers-extension/assets/59027566/5ce267ce-37de-4c14-bd3e-e1cb50c8e8dc)

### Value
Ability for users to see Guided Answers in Welcome Page

### Architecture Elaboration
Does it requires architecture elaboration?

### Tasks
- [ ] Task 1

**Comment by carwelsh** [comment]
@unseen1980 

The name of the quick link will be "Guided Answers extension" and the description should be "Interactive documentation designed to help troubleshoot issues"

@theStiggySpd @ritarora FYI

**Comment by theStiggySpd** [comment]
This is done and Guided Answers will show up in Quick Links in SBAS Home Page
