### ISSUE TITLE
BUG - Click on link instructions is not clickable

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#512]
### Related Feature
Feature request: _issue number_

### Description
The guided answers shared instructions  provides instructions to click on the link for VSCode users however the link is not clickable as it is wrapped in quotations.

### Steps to Reproduce
1. Go to GA content
2. Click on copy link with instructions icon
3. Paste instructions 

### Expected results

Click on link for VSCode link

### Actual results

VSCode link is not clickable as per instructions.

To resolve your reported issue, open Guided Answers extension by SAP, and follow the steps mentioned in the guide.
->If your IDE is VSCode, please click on the following link: "vscode://saposs.sap-guided-answers-extension#/tree/3046/actions/45995:45996"  
->If your IDE is SAP Business Application Studio, then:
  a. Launch Guided Answers via the command "SAP: Open Guided Answers"
  b. Paste the following guide shortlink into the search input field: "vscode://saposs.sap-guided-answers-extension#/tree/3046/actions/45995:45996"

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by oliversberzs** [comment]
@ritarora this seems to be fixed already
