### ISSUE TITLE
BUG - Actually use Secondary Button

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#521]
Hey all,

This button here (and all of the secondary buttons)

<img width="614" alt="Screenshot 2023-05-31 at 09 20 16" src="https://github.com/SAP/guided-answers-extension/assets/44162846/adbb493e-9151-4c56-8125-abf5296da6e7">

It is not actually using our official `ui-components` Secondary Button style. This makes it a bit wonky, you can see that colour contrast is not good.

Here's the official Secondary Button:

<img width="401" alt="Screenshot 2023-05-31 at 09 21 54" src="https://github.com/SAP/guided-answers-extension/assets/44162846/dbb29b1c-413e-4e46-82a7-e38eea9db6eb">

The main difference is that the real Secondary Button uses `color: var(--vscode-button-secondaryForeground);` for the font.

Can we please fix this?

**Comment by unseen1980** [comment]
Hi @gpeuc, if I use the ```secondaryForeground``` then the light modern looks ok but the light (visual studio) is not looking right
![Screenshot 2023-06-06 at 11 18 09](https://github.com/SAP/guided-answers-extension/assets/2386570/59690e9e-0ced-417a-815a-a046eac8af95)

![Screenshot 2023-06-06 at 11 19 55](https://github.com/SAP/guided-answers-extension/assets/2386570/837cbf95-bec3-4e0a-8b08-ef513cc91312)

**Comment by oliversberzs** [comment]
@gpeuc done & merged

**Comment by theStiggySpd** [comment]
Tested with https://github.com/SAP/guided-answers-extension/releases/tag/sap-guided-answers-extension%401.23.6
Thanks for the fix @oliversberzs
