### ISSUE TITLE
FEATURE - EXT - Smart Home Page - Phase 1 

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#531]
**As a user, I would like to be presented with Guided Answer content that is relevant to me be it the last content I visited, my bookmarks or content that relevant to my development  set up so that I can quickly find content that will resolve my issues faster**

### Description

Phase 1 of the new smart home page will show end users 

1. Content they last visited FEATURE - Ability to see Last visited tree/node in GA home page #541
2. Saved bookmarks 
3. Quick Filters that is relevant to the end users dev space. ( SBAS only) (FEATURE - GA Home Page: Add ability to show Quick filters in SBAS for Fiori dev space #545)

The Last Visited, Bookmarks and Quick Filters will be displayed in separate sections on the Home page.  If there is no content to be displayed in these sections they will not be displayed on the Home page. 

On opening the Guided Answers extension the smart Home page will always be displayed to the end users. 
When a Guided Answer is opened the Home link will always return end users to the Smart Home Page
The Step back link will always navigate the user to their previously viewed page in the Guided Answer extension.
The SAP Logo displayed in the search returned list will also navigate the end user to the Smart Home Page.

_Last visited_
Last visited content will only display if the end user has  used the Guided Answers extension before and has visited a Guide. 

The last visited content will always be updated with the last Guided Answer node the end user visited. It will only show the last node visited. On selection of the last visited Guided Answer node the user will be navigated to that node. 

_Bookmarks_
Bookmarks will only display if the end user has bookmarked Guided Answer content previously. 

The end user can remove their bookmarks from the home page without having to navigate to the Guided Answer content. When an end user removes a bookmark it will remain listed in the bookmarked list but will no longer be marked with a book mark star. When the user navigates away from the smart home page and then return then the bookmarked content will be no longer be displayed in the bookmark list. 

_Quick Filters_ 
Dependent on the end users dev space in SAP Business Application Studio Guided Answers can be filtered based on the Fiori Dev space components. On clicking a quick filter the Guided Answers content will be filtered on a set of components. The Guided Answers will be displayed in a list with the filters applied displayed. 

Currently there is not quick filters for VS Code just SAP Business Application Studio 

### Technical Design
In the backend we will save 5 of the last visited Guided Answers nodes but only the very last visited node will be displayed. 

### Visual Design 

The Guided Answer search is centered.
There will be up two columns displaying the different sections. Each column can display up to 2 sections. 
If only 2 sections are displaying only one column will displayed and it will be centered. 

https://www.figma.com/file/XSZw3w81MYY0QPe1BoUcBO/Guided-Answers?type=design&node-id=0-1&t=FLF3rPRRQoiCKIcU-0

### Interaction Design 
_VSCODE_
1. Users Opens GA - Smart Home Page is displayed only a centered search is displayed,
2. User searches for a guide
3. User selects a guide
4. User navigates through a guide
5. User bookmarks a node in the guide
6. User clicks Home - Smart Home Page is displayed with a centered search input field , a section show the last visited node and a section showing the bookmarked guide. 
7. User closes GA
8. User opens GA - Smart Home Page is displayed with a centered search input field , a section show the last visited node and a section showing the bookmarked guide. 
9. User clicks on star beside the  bookmarked guide - Bookmark section displays the bookmark but the star is no longer filled with yellow. 
10 Users clicks last visited - User is navigated to the last visited node
11. User navigates to another node in that tree - Last updated guided is updated
12. User clicks 'Home' - Smart Home Page is displayed with a centered search input field , a section showing the last visited node, the bookmark section is no longer displaying. 
13. User closes GA
14. User opens GA - Smart Home Page is displayed with a centered search input field, a section showing the last visited node, the bookmark section is no longer displaying. 
15. User enters input in search input field- Search results are displayed
16. User clicks on the SAP logo - Smart Home Page is displayed with a centered search input field is displayed, a section showing the last visited node
16  User enters input in search input field- Search results are displayed
17. User clears the search input using backspace or clicks on the 'X' icon in the search in put - ??

_SBAS_
1. Users Opens GA - Smart Home Page is displayed only a centered search  and Quick filters section is displaying showing a filter for the following components.
2. User click on quick filter - List of guides are displayed to user with the filters applied.  
5. User selects a guide
6. User navigates through a guide
7. User bookmarks a node in the guide
8. User clicks Home - Smart Home Page is displayed with a centered search input field , a section showing the last visited node ,section showing the bookmarked guide and a **section showing quick filters**. All sections are centered.
9. User closes GA
10. User opens GA - Smart Home Page is displayed with a centered search input field , a section showing the last visited node ,section showing the bookmarked guide and a **section showing quick filters**. All sections are centered.
11. User clicks on star beside the  bookmarked guide - Bookmark section displays the bookmark but the star is no longer filled with yellow. 
10 Users clicks last visited - User is navigated to the last visited node
12. User navigates to another node in that tree - Last updated guided is updated
13. User clicks 'Home' - Smart Home Page is displayed with a centered search input field , a section showing the last visited node  and a **section showing quick filters**. All sections are centered. Bookmark section is no longer being displayed. 
14. User closes GA
15. User opens GA - Smart Home Page is displayed with a centered search input field , a section showing the last visited node  and a **section showing quick filters**. All sections are centered. Bookmark section is no longer being displayed.
16. User enters input in search input field- Search results are displayed
17. User clicks on the SAP logo - Smart Home Page is displayed with a centered search input field , a section showing the last visited node  and a **section showing quick filters**. All sections are centered. Bookmark section is no longer being displayed
16  User enters input in search input field- Search results are displayed
18. User clears the search input using backspace or clicks on the 'X' icon in the search in put - ??

### Acceptance Criteria
1. User can search for a guide using the Smart Home page
2. After use of the extension , the user can see their last visited guides
3. After bookmarking guides, the user can their bookmarked guides on the smart home page
4. The smart home page displays a quick filter for Fiori Dev Spaces in SBAS. 
5. The user can un bookmark a guide from the Smart Home page
6. The user can navigate back to the smart home page using the Home button or the SAP logo. 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment]
@oliversberzs FYI - As quick filters will only contain one filter to begin with the Quick filters will now be shown under the last visited, bookmarks section on the home page. All three sections will be centered  under the search input.

**Comment by oliversberzs** [comment]
new home layout has been merged and is behind the beta features toggle

**Comment by oliversberzs** [comment]
last visited sections has been merged

**Comment by theStiggySpd** [comment]
@oliversberzs As part of this ticket, please make sure that in GA, after providing outcome/feedback for a particula tree, whether an issue has solved the problem or not, from the pop up, Home button should take us to new GA Home Page.
