### ISSUE TITLE
BUG - Search results seems duplicated

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#535]
### Related Feature
Feature request: _issue number_

### Description
A clear description of what the bug is.

### Steps to Reproduce
1. Launch Guided Asnwers
2. Search for `SAP Fiori tools`

### Expected results
Trees are noot duplicated

### Actual results
Trees are duplicated

### Screenshots
![image](https://github.com/SAP/guided-answers-extension/assets/59027566/3c3fcee7-9e20-44c9-bfe0-db754988e2b0)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by Klaus-Keller** [comment]
When I'm accessing the API directly I do not see duplicate entries:
https://ga.support.sap.com/dtp/api/v5/trees/%22SAP%20Fiori%20tools%22?product=&component=&responseSize=18&offset=0

```json
{
  "resultSize": 3,
  "trees": [
    {
      "SCORE": 0.94,
      "TREE_ID": 3046,
      "TITLE": "SAP Fiori tools",
      "DESCRIPTION": "This is a troubleshooting guide to solve the issues while using SAP Fiori tools",
      "AVAILABILITY": "PUBLIC",
      "FIRST_NODE_ID": 45995,
      "PRODUCT": "SAP Fiori tools",
      "COMPONENT": "CA-UX-IDE"
    },
    {
      "SCORE": 0.82,
      "TREE_ID": 3337,
      "TITLE": "SAP Fiori tools - Application Preview",
      "DESCRIPTION": "This is a troubleshooting guide to solve the issues related to application preview while using SAP Fiori tools",
      "AVAILABILITY": "PUBLIC",
      "FIRST_NODE_ID": 52881,
      "PRODUCT": "SAP Fiori tools",
      "COMPONENT": "CA-UX-IDE"
    },
    {
      "SCORE": 0.36,
      "TREE_ID": 3348,
      "TITLE": "Configuration of SAP Fiori Application",
      "DESCRIPTION": "Maintaining and Adding annotations",
      "AVAILABILITY": "PUBLIC",
      "FIRST_NODE_ID": 53055,
      "PRODUCT": "SAP Fiori tools",
      "COMPONENT": "CA-UX-IDE"
    }
  ],
  "productFilters": [
    {
      "PRODUCT": "SAP Fiori tools",
      "COUNT": 3
    }
  ],
  "componentFilters": [
    {
      "COMPONENT": "CA-UX-IDE",
      "COUNT": 3
    }
  ]
}
```

**Comment by Klaus-Keller** [comment]
Ok, I think I found the issue. Prepared PR https://github.com/SAP/guided-answers-extension/pull/537
