### ISSUE TITLE
FEATURE - GA Home Page: Add ability to show Quick filters in SBAS for Fiori dev space

### ISSUE THREAD

**Issue by theStiggySpd** [SAP/guided-answers-extension#545]
_As a **developer using Guided Answers in Fiori dev space in SAP Business Application Studio**,
I want to see a list of PRODUCTS and COMPONENT as quick filters in new GA Home Page ,
so that I can click on the any of the suggested filter for faster and accurate search results_

### Description

- The new GA Home Page will show a `Quick Filters` section. Later we will expand it and add Product and component combination. For now, we can just show list of components
![image](https://github.com/SAP/guided-answers-extension/assets/59027566/655d5843-d327-4a5e-ac91-976d333d62d7)

- For `SAP Fiori` dev space, these are the software components which needs to be shortlisted: 
`CA-UX-IDE`
`CA-FE-FLP-EU`
`CA-FE-FLP-DT`
`CA-FE-FAL`
`CA-UI2-INT-BE`
`CA-UI2-INT-FE`
`CA-UI2-THD`

### Technical Design
TBA 

### General User Flow
- User launches GA in SBAS Fiori dev space
- User is shown the GA Home Page with quick filters which are shortlisted component
- User will click on the suggested filter (Currently, it will be all the components)
- User is taken to Search Screen where filters applied are shown
- User searches for something
- Filters will NOT be cleared NOW
- Search should be done with the filters applied 

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a dev space of type `SAP Fiori` open in SBAS
**when** I open Guided Answers
**then** the Quick Filters section should show components shortlisted for Fiori dev space

### Tasks
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by oliversberzs** [comment]
@carwelsh @ritarora done & merged
