### ISSUE TITLE
BUG - Icon fix and icon replacement

### ISSUE THREAD

**Issue by gpeuc** [SAP/guided-answers-extension#562]
Hi folks,

We've noticed that some of the icons in GA are coming from some 3rd party library, and not from our icons.tsx file. 

One example is this star, which in implementation is coming from somewhere else:

<img width="95" alt="Screenshot 2023-08-18 at 10 11 29" src="https://github.com/SAP/guided-answers-extension/assets/44162846/22233781-cf5d-40d2-9ce5-410a28a2a922">

And in designs, you can see it has softer arms:

<img width="226" alt="Screenshot 2023-08-18 at 10 12 09" src="https://github.com/SAP/guided-answers-extension/assets/44162846/fc3b6dc0-a1e8-4ec1-adc0-b3f869a9212f">

This is not really acceptable. The icons that we drew (and that are actually placed in [icons.tsx](https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/components/Icons.tsx) file) should be the ones that are used in the app. We should not be secretly using 3rd party icons while our designers are actually manually drawing the icons.

- - - - -

Once the icons are replaced for our home-made icons, we need to tweak them, as it seems some paddings are broken. The buttons should be 24 × 24 rectangles, with icons placed in the middle. And the icon+label button should have same left-right padding, and be 24px tall.

<img width="502" alt="Screenshot 2023-08-18 at 10 14 42" src="https://github.com/SAP/guided-answers-extension/assets/44162846/6ae599ee-734b-46cc-aeb6-a2d9c857b58e">

Currently it's all over the place:

<img width="271" alt="Screenshot 2023-08-17 at 14 39 50" src="https://github.com/SAP/guided-answers-extension/assets/44162846/3fe6a6ed-bc86-4095-9e59-3d51c7bfc21c">

<img width="289" alt="Screenshot 2023-08-17 at 14 39 53" src="https://github.com/SAP/guided-answers-extension/assets/44162846/863529d1-3744-413d-b8cc-b34459d9b211">

<img width="322" alt="Screenshot 2023-08-17 at 14 39 47" src="https://github.com/SAP/guided-answers-extension/assets/44162846/60bf023a-1604-4ff7-b424-d38404934796">

<img width="117" alt="Screenshot 2023-08-18 at 10 18 32" src="https://github.com/SAP/guided-answers-extension/assets/44162846/eca0267d-5823-4687-8bc7-f9c126d3b1f0">

- - - - -

- [ ] Replace icons with our home-made icons
- [ ] Fix the icon buttons and icon+label buttons

- - - -

@oliversberzs @unseen1980 @carwelsh

**Comment by gpeuc** [comment]
Just in case: the star icon (both variants). Please remember to replace the colours in them when adding to icons.tsx to our internal colour variables. Yellow is: `var(--vscode-editorLightBulb-foreground)`

**Comment by oliversberzs** [comment]
@ritarora @carwelsh fixed & merged
