### ISSUE TITLE
BUG - EXT - HTML Enhancments not appearing as clickable link

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#590]
### Description
HTML Enhancements not appearing in Guided Answer Content 

### Steps to Reproduce
1. Go to SBAS
2. Create Fiori Dev Space
3. Open GA
4. Search 'vscode://saposs.sap-guided-answers-extension#/tree/3046/actions/45995:48363:53594:48366'

### Expected results

Fiori: Open Environment Check  appears as a clickable like 

### Actual results

Fiori: Open Environment Check does not appear as a clickable link.

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by hitesh-parmar** [comment]
Hi @carwelsh, As the scenario is working, could we close this issue?

**Comment by carwelsh** [comment]
@hitesh-parmar  Yes, this can be closed. A user story was created for this bug.
