### ISSUE TITLE
US - EXT - Exception Handling for when GA external website is down

### ISSUE THREAD

**Issue by sanat-thukral** [SAP/guided-answers-extension#85]
### Description (include screenshots)
This TBI will help us better handle when [GA external](https://ga.support.sap.com/dtp/viewer/) is down. As we have a core dependency on their API. 
![Screenshot 2022-05-24 at 10 30 39 a m](https://user-images.githubusercontent.com/104602674/169999873-b4142431-eb45-4025-9082-44afdaf8d9bd.png)

![Screenshot 2023-03-21 at 11 04 48](https://user-images.githubusercontent.com/9609226/226588244-b51136e5-d866-4234-9c0e-afd4ed5432f5.png)

### Value
The goal is to make users aware when the Guided Answers web application is not available. 

The following message should be displayed 

Guided Answers is currently unavailable ( BOLD)
Please Try again later 
Icon- Search icon with sad face 

[
![Screenshot 2023-03-21 at 11 03 48](https://user-images.githubusercontent.com/9609226/226587831-e2bd8357-0793-44c6-9fe2-f62c5683ad41.png)
](url)

### Architecture Elaboration
- Do we get an error message from the API when it's down
- What error should we provide to the user

### Tasks
- [ ] check if GA API is down
- [ ] Generate UI to present to the user 
Do we need anything else?

**Comment by oliversberzs** [comment]
@carwelsh @ritarora done & merged

**Comment by theStiggySpd** [comment]
@oliversberzs Was this done? I do not see an linked pr?

**Comment by oliversberzs** [comment]
@theStiggySpd yes, it was done, the PR is linked right above. it's this one: https://github.com/SAP/guided-answers-extension/pull/473
