### ISSUE TITLE
FEATURE - UX enhancements to Content Tree component in GA content pages

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#91]
### Description

Update  GA Content Tree to have new look and feel

1. Update 'Go Back' link to be 'Home'
2. Update tree to have new look and feel ,clickable and responsive

### Visual Designs

New Design
![Screenshot 2022-05-25 at 13 15 25](https://user-images.githubusercontent.com/9609226/170259706-2dfc74ce-1cac-4507-bec5-0de8cb35bf19.png)

Old Design
![Screenshot 2022-05-25 at 13 20 34](https://user-images.githubusercontent.com/9609226/170260607-94f236bd-40e0-4f85-810a-eb0e6a9664fd.png)

### Technical Design
https://www.figma.com/file/XSZw3w81MYY0QPe1BoUcBO/Guided-Answers?node-id=0%3A1

Fonts , SVGs etc

### Acceptance Criteria
GA Content Tree has new look and feel 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by theStiggySpd** [comment]
@carwelsh One of the essence of Guided Answers is guidance through a branch and see how its linked. I feel tree component is missing that "linked" theme from new proposal 
![image](https://user-images.githubusercontent.com/59027566/172673726-cd3a33c2-3655-45db-87e9-730f70ee5474.png)

Its not a `steps` navigation or `table of contents`. 
![image](https://user-images.githubusercontent.com/59027566/172674092-e3baeb93-c196-47c9-b348-63b275329125.png)

Can we please weigh in some more alternatives before this goes into development.
@Goran Thoughts?

**Comment by theStiggySpd** [comment]
[sap-guided-answers-extension-0.3.3.vsix.zip](https://github.com/SAP/guided-answers-extension/files/8952885/sap-guided-answers-extension-0.3.3.vsix.zip)

Based on preliminary version provided by @unseen1980 here are my comments. Some feedback might not be in original spec, but lets see if we can resolve here after finalizing with UX experts:

- When screen width is small, the step number should show step title as tooltip. Currently its not and not very intiutive if I am few steps down and want to know titles few steps back. We had similar UX discussion for SAP Fiori tools Guided Development. @gpeuc Can you please advise.
![image](https://user-images.githubusercontent.com/59027566/174901265-337a4e4c-fbc6-4564-81ed-3434d0d70af9.png)

- The `Step back` link gets placed weirdly in almost in middle. @unseen1980 Can we please fix it as part of this feature/branch?
![image](https://user-images.githubusercontent.com/59027566/174901798-a5d7354a-a663-445f-95c2-b89fbbb1c3df.png)

- The `Home` icon looks small and not super nice. Can we play around to make it better? @gpeuc ?
Also noticed that we have new design for `Home` icon to be converted into Icon+text (All Answers) . I am hoping may be this solves the super small icon issue. 
BTW @carwelsh I noticed that by mistake we have  Update 'Go Back' link to be 'All Answers' in the description. Can we please correct it?
![image](https://user-images.githubusercontent.com/59027566/174902084-f2526769-5449-4f82-8469-0474b5e98169.png)

**Comment by theStiggySpd** [comment]
Thanks @unseen1980 for taking care of the comments. With the new version to test, I noticed one glitch (not sure if it was already there.

When you are like in step >3 depth, I noticed that the step connectors in the tree component starts vanishing. 
Please see a snapshot here (Notice the missing lines in the tree):
![image](https://user-images.githubusercontent.com/59027566/175219091-83b7e471-b06a-41ba-adf6-ecc32d21dc6d.png)

**Comment by gpeuc** [comment]
Oh right. @unseen1980 We need to construct the connector differently. Probably some :after so that it always positions itself after the DIV no matter how many lines it has. I guess that might work.
