### ISSUE TITLE
FEATURE - EXT -  Allow users to input whether the guided answer 'solved' or 'not solved' their issue

### ISSUE THREAD

**Issue by carwelsh** [SAP/guided-answers-extension#96]
**As a user, I want to indicate whether the guided answer solved or did not solve my issue so that I can inform the content creators that the content was or was not useful**

### Description

The last page/node of a guided answer should allow the user to indicate if the the guided answer solved or did not solve their issue.

Two buttons should display 'This solved my issue'  and 'This did not solve my issue' . Visual designs below 

On click of 'This solved my issue' a pop up should display to the user informing the user that the GA team are glad this guide was of use. The text for the pop is below. The user can click 'HOME' or 'CLOSE' the pop up. Clicking 'HOME' returns the user to the GA answer home page where the user can search for another guide e.g. blank search field.  On clicking 'CLOSE' the user is returned back to the last page/tree of the guided answer. 

On click of 'This did not solve my issue' , the user is navigated to new page/node where the GA default outcomes are displayed to the user. On click of a default option , the options url is opened in the users browser. The default text for this new page is documented below. This default node/page should also appear in the tree component underlined in red.  Visuals are below. 

Start an Expert Chat - https://launchpad.support.sap.com/#/expertchat/create
Schedule an Expert - https://launchpad.support.sap.com/#/sae
Open an Incident - https://launchpad.support.sap.com/#/incident/create
Ask the SAP Community - https://answers.sap.com/index.html
Search for another Guided Answer - Return to the home page

**Note**:  Currently the API does not return any buttons or outcomes as parts of the last node, so by default we show the 'Solved' and 'Not Solved' buttons when there are no outcomes returned.

**Note**: The GA content creator can choose to show custom outcomes and an email  option rather than the GA default outcomes. When the API is updated to return this information we can update this in the extension until then we will just show the default options.  Another issue will be created to handle the custom and email options

**Note**: The 'solved', 'not solved' feedback will not be submitted back to GA until API is available to do so. When the API is available it will be integrated and the user's actions will be captured. 

### Text for the Pop Up

Solved Pop up

We are glad to hear that your issue has been resolved and we hope
you enjoy using the Guided Answers application.

Not Solved Pop Up

Title : Issued is not resolved
Description: We are sorry to hear that your issue is not yet resolved.
There are several options for getting further assistance:
Options: 
Start an Expert Chat - https://launchpad.support.sap.com/#/expertchat/create
Schedule an Expert - https://launchpad.support.sap.com/#/sae
Open an Incident - https://launchpad.support.sap.com/#/incident/create
Ask the SAP Community - https://answers.sap.com/index.html
Search for another Guided Answer - Return to the home page

### Visual Designs 

Solved/Not Solved Final Page
![Screenshot 2022-06-13 at 13 58 39](https://user-images.githubusercontent.com/9609226/173359145-f3118ce9-2bb7-4c93-8570-268a68167cf1.png)

Solved Pop Up 
![Screenshot 2022-06-13 at 13 58 50](https://user-images.githubusercontent.com/9609226/173359180-7d426508-acfa-44ec-9c5d-6bea9d48c3ad.png)

Not Solved Page 
![Screenshot 2022-06-13 at 13 59 02](https://user-images.githubusercontent.com/9609226/173359205-10e202bd-cdd3-4966-b084-969ef0d93a3d.png)

### UX Design
https://www.figma.com/file/XSZw3w81MYY0QPe1BoUcBO/Guided-Answers?node-id=0%3A1

### Technical Design
Currently an API is not available to submit this feedback or show what the guided answers final outcomes are . There will be a story to integrate an API with this functionality when it is available.

### Acceptance Criteria
1. User can click 'This solved my issue ' or ' This did not solve my issue' according to the visual design
2. On click a pop up informs that the GA team are glad or disappointed depending on what the user clicked. 
3. The user can click Home or Close on the pop 
4. On click of 'Home' the user is returned to the home page to conduct a new search 

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by carwelsh** [comment]
@ritarora - Please review :)

**Comment by carwelsh** [comment]
@sanat-thukral - You will need to check with Christos how we can fake a node in the tree component  as this something that will not be returned by the API.

**Comment by ritarora** [comment]
thanks @carwelsh, updated the main issue with a couple of things
